# Generated by Django 5.0.6 on 2024-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='text_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='in_correct',
            field=models.BooleanField(default=True),
        ),
    ]
